"""changed the user_token to user_email in llm_response table

Revision ID: 1897d6c03919
Revises: 47abc1691167
Create Date: 2026-07-14 12:20:14.696036

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1897d6c03919'
down_revision: Union[str, Sequence[str], None] = '47abc1691167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_response', sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('llm_response', 'user_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_response', sa.Column('user_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('llm_response', 'user_email')
    # ### end Alembic commands ###
