"""added the status field in the documents table

Revision ID: bea1abb33651
Revises: 1897d6c03919
Create Date: 2026-07-17 13:02:19.992870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea1abb33651'
down_revision: Union[str, Sequence[str], None] = '1897d6c03919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'documents',
        sa.Column(
            'status',
            sa.String(),
            nullable=False,
            server_default='pending'
        )
    )

    op.alter_column(
        'documents',
        'status',
        server_default=None
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###
